# Generated by Django 2.2 on 2019-10-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'disque', 'verbose_name_plural': 'disques'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'artiste', 'verbose_name_plural': 'artistes'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'réservation', 'verbose_name_plural': 'réservations'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'prospect', 'verbose_name_plural': 'prospects'},
        ),
        migrations.AlterField(
            model_name='album',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponible?'),
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date création'),
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.URLField(verbose_name='maquette'),
        ),
        migrations.AlterField(
            model_name='album',
            name='reference',
            field=models.IntegerField(null=True, verbose_name='référence'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='contacté?'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date création'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
    ]
