language: python
python:
  - '3.6'
  - '3.7'

before_script:
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test